//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLLC.CDS.Test
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.42+g8b6f5d8")]
	public enum ccllc_transactionrequirement_ccllc_TransactionRequirementTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Eligibility = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prerequisite = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Validation = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Evidence = 8,
	}
}