//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLLC.CDS.Test
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.42")]
	public enum EnvironmentVariableDefinition_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connectionreference = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JSON = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 100000000,
	}
}