//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\scott\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://orge83f40b7.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CCLLC.CDS.Test" /out:"E:\Repos\CCLLCCDSFieldEncryption\CCLLC.CDS.FieldEncryption.Test\Entities\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"scott@colsoncode.com" /password:"***********" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace CCLLC.CDS.Test
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.42")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.Account> AccountSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.BusinessUnit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.BusinessUnit> BusinessUnitSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.BusinessUnit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.EnvironmentVariableDefinition"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.EnvironmentVariableDefinition> EnvironmentVariableDefinitionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.EnvironmentVariableDefinition>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.EnvironmentVariableValue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.EnvironmentVariableValue> EnvironmentVariableValueSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.EnvironmentVariableValue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.Role> RoleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.SystemUser> SystemUserSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CCLLC.CDS.Test.WebResource"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CCLLC.CDS.Test.WebResource> WebResourceSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CCLLC.CDS.Test.WebResource>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
}